ratings:
  namespace: student9-bookinfo-uat
  image: ghcr.io/kuraigi/bookinfo-ratings
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.uat.opsta.net
  path: "/student9/ratings(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-uat-ratings-mongodb:27017/ratings
  MONGO_DB_USERNAME: ratings
  COMMIT_SHA: CHANGEME
extraEnvSecret:
  MONGO_DB_PASSWORD:
    bookinfo-uat-ratings-mongodb-secret: mongodb-password